### ISSUE TITLE
Further improve and complement figures

### ISSUE THREAD

**Issue by Peter9192** [eucp-project/atlas#15]
- Address open comments in #14
- Include CMIP5 figures if available
- Add placeholder for unavailable figures or make it impossible to select them
- ...

**Comment by geek-yang** [comment]
Regarding the placeholder for unavailable figures, after some googling, it seems that an easy and clean solution will be the `@error` handler in nuxt, see the [post](https://forum.vuejs.org/t/how-to-require-a-image-only-if-it-exist-or-else-require-the-default/67523). However, it does not work in our case. I tried most of the suggested solutions I could find (e.g. like [this](https://github.com/nuxt/nuxt.js/issues/5493)). Still did not get anything working for me.

**Comment by geek-yang** [comment]
An alternative would be, load image via computed property and use if/else pair in the `computed: {}` function. But it is a bit nasty.

**Comment by geek-yang** [comment]
One more idea, we can place the `img` inside the `div`. Set the `div` background to be the placeholder image using css. And move all the figures from assets to static (which means, we do not load figures dynamically via webpack, but statically). Then, when the images are missing, it only returns an error in the console, but the page is still there, which will display nothing but shows the background.

Again, just some thought, but the solution is still not perfect. We have to discuss it a bit.

**Comment by Peter9192** [comment]
What happened to the idea we started off with, adding a callback to update the figure when the selection was changed? Why did it not work?

**Comment by Peter9192** [comment]
> And move all the figures from assets to static (which means, we do not load figures dynamically via webpack, but statically)

Probably fine, but not sure it's needed.

> One more idea, we can place the `img` inside the `div`

We used to have that before, but we changed to a div with background image because it was easier to get the responsive stretching right.

**Comment by geek-yang** [comment]
@Peter9192 Your solution #22 looks very good to me. Indeed my attempt was to use the error event handler and place the fallback there. But the nuxt option (`@error`) does not work for no reason. But your code simply does what I want. I will stick to it instead. Thanks for the solution!
