### ISSUE TITLE
Cannot find module '@nuxtjs/fontawesome'

### ISSUE THREAD

**Issue by SarahAlidoost** [eucp-project/atlas#54]
A dependency is added by this [commit](https://github.com/eucp-project/atlas/commit/59ac88f597355200947dce62ea376ee10520f8fd). I found [this instruction](https://www.npmjs.com/package/nuxt-fontawesome#setup) to install it. Is it the best way? Shall we add how to install this dependency to readme?

**Comment by Peter9192** [comment]
When you first clone the repo, you have to do `npm install`. Whenever a dependency is added, you have to run that same command again.
