### ISSUE TITLE
Add time periods to FAQ

### ISSUE THREAD

**Issue by Peter9192** [eucp-project/atlas#74]
The maps show the “differences between 2041-2060 mean conditions, with respect to the 1995-2014 present day baseline”.  It would be good to clarify this in the “What do these maps show?” about section, and perhaps also reflect this in the individual figure labels.

**Comment by SarahAlidoost** [comment]
Figure labels (title) are generated using `maps_creator_atlas_data.py `. It means all maps should be re-generated to show time periods.
